### PR TITLE
Update CONSTS to direct developers to use role instead of accessibilityRole (#31500)

### PR DESCRIPTION
**Pull request by trevor-coleman**
This fixes the issue with ROLE and ACCESSIBLITY_ROLE identified earlier and discussed on Slack.

It makes the following changes:

# Changes to `CONST.ts`
1. Reverts `CONST.ACCESSIBILITY_ROLE.TEXT` to the value `'text'`
2. Adds deprecation warnings on `CONST.ACCESSIBLITY_ROLE` and all properties
3. Creates the `CONST.ROLE` object with JSDoc comments 

# Fixes to Components

## Simple find-replace

The majority of components were fixed using a simple find and replaced that made the following change

Replace: `role={CONST.ACCESSIBILITY_ROLE` with `role={CONST.ROLE`

For example:

`role={CONST.ACCESSIBILITY_ROLE.BUTTON}` would become `role={CONST.ROLE.BUTTON}`

## Specific Cases

| Description | Why Change Was Made | Before | After |
|-------------|---------------------|--------|-------|
| Components using `TEXT` to mean `PRESENTATION` | Aligned with correct key in CONST.ROLE | `role={CONST.ACCESSIBILITY_ROLE.TEXT}` | `role={CONST.ROLE.PRESENTATION}` |
| Inappropriate use of `IMAGEBUTTON` | `IMAGEBUTTON` only available in `accessibilityRole`. Corrected property to `accessibilityRole` and pointed to the right const | `role={CONST.ACCESSIBILITY_ROLE.IMAGEBUTTON}` | `accessibilityRole={CONST.ACCESSIBILITY_ROLE.IMAGEBUTTON}` |
| Inappropriate use of `ADJUSTABLE` | `adjustable` is not available in `role` but is in `accessibilityRole`. Reverted the value and updated prop to reflect correct usage | `role={CONST.ACCESSIBILITY_ROLE.ADJUSTABLE}` | `role={CONST.ROLE.SLIDER}` |
| Use of non-existent `ACCESSIBILITY_ROLE.IMAGE` | Replaced with valid `role` value  | `role={CONST.ACCESSIBILITY_ROLE.IMAGE}` | `role={CONST.ROLE.IMG}` |

Note: In the IMAGEBUTTON Case, I thought it was best to preserve the `imagebutton` role information, and minimize the number of changes, rather than try to decide on a case-by-case basis what an appropriate replacement would be. 

### Fixed Issues

$ 
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by cdanwards** [comment]
@trevor-coleman looks like the linter isn't happy! And some conflicts

**Comment by cdanwards** [comment]
Also we should probably point it at a different branch than `main` and then PR that branch against `ExpensifyApp/main` so it can go through their process.

**Review by cdanwards — COMMENTED** [review]
Love the detail in documentation

**Comment by trevor-coleman** [comment]
Linter passing -- going to make that new branch now.

**Comment by trevor-coleman** [comment]
@cdanwards  --  lints are passing, and this is now against a feature branch. I think she's ready to go.

**Comment by trevor-coleman** [comment]
> Love the detail in documentation

Yeah when I do big find-replaces like this I like to document the edge cases to (hopefully) make it easier to review.

**Review by cdanwards — APPROVED** [review]
:shipit:

**Pull request merged**
