### PR TITLE
Add sync ios deployment target to Podfile

### PR DESCRIPTION
**Pull request by ryanlntn**
This adds ios deployment target syncing to the Podfile. This isn't baked in to Cocoapods but since [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) is a dependency of Cocoapods we can script this sort of thing ourselves.

### CODE REVIEW

**Review by cdanwards — APPROVED** [review]
Just getting around to take a look at this. ChatGPT helped my understand the Ruby parts but looks good to me!

**Comment by lindboe** [comment]
Is this still relevant? I thought we had a unified configuration in the branch already?

**Comment by ryanlntn** [comment]
@lindboe Never really was that relevant since on iOS the target always wins. We had just noticed Expensify was inconsistent between targets here. This was just noodling to make it possible to set them all from the Podfile but ultimately it's not necessary.

**Comment by lindboe** [comment]
Ah, sorry, I misunderstood then, I thought that [the :inherit change](https://github.com/infinitered/ExpensifyApp/commit/22dc758d3754b988eeda37386ee8796b6be0d20f) also covered the target version

**Pull request closed without merging**
