### PR TITLE
Implement Base Android Sharing

### PR DESCRIPTION
**Pull request by trevor-coleman**
# Reimplent Basic Android Sharing 

This PR implements basic android sharing. It follows the `react-native-share-menu` android instructions and makes a few patches to android build scripts to make it work.

## Patch `react-native-share-menu`: `build.gradle` 

- Updates the build script to be compatible with current versions of react native -- using `safeExtGet('targetSdkVersion',rnsmDefaultCompileSdkVersion)` so that we won't need to manually patch for every update

## Patch `react-native-share-menu`:`ShareMenuModule.java`

- add some required methods as described

### CODE REVIEW

**Comment by trevor-coleman** [comment]
This is now working on Android.

**Review by lindboe — CHANGES_REQUESTED** [review]
I think we should update the "REMOVE ME" commit; we can't easily go back and rebase once things are merged into the feature branch. At the very least commit to it and don't say "REMOVE ME", but indicate it's a temporary fix, or improve it now.

I believe as it stands, the app wouldn't open on the feature branch without this fixed; which means we should've brought this fix into the earlier PR. Sorry, I forgot about that part this morning.

**Comment by trevor-coleman** [comment]
OK I can fix that on Monday

**Comment by trevor-coleman** [comment]
@lindboe -- Took a look at the temporary thing. -- the purpose of that clause is to catch cases where there is no share data, so it seems fine to leave it in. We'll want to extract that to an `isShareDataEmpty()` method or something eventually.

**Pull request merged**
